-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 09:56:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yii2-shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yii2-shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yii2-shop` DEFAULT CHARACTER SET utf8 ;
USE `yii2-shop` ;

-- -----------------------------------------------------
-- Table `yii2-shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2-shop`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `phone` CHAR(11) NOT NULL COMMENT '电话',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户';


-- -----------------------------------------------------
-- Table `yii2-shop`.`goods_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2-shop`.`goods_order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sn` VARCHAR(45) NOT NULL COMMENT '序号',
  `total_price` INT NOT NULL COMMENT '总价',
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_goods_order_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_goods_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `yii2-shop`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '订单';


-- -----------------------------------------------------
-- Table `yii2-shop`.`goods_order_snapshot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2-shop`.`goods_order_snapshot` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL COMMENT '快照内容',
  `goods_order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fk_goods_order_snapshot_goods_order_idx` (`goods_order_id` ASC),
  CONSTRAINT `fk_goods_order_snapshot_goods_order`
    FOREIGN KEY (`goods_order_id`)
    REFERENCES `yii2-shop`.`goods_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '快照';


-- -----------------------------------------------------
-- Table `yii2-shop`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yii2-shop`.`goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '商品名字',
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
